/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as AppSignupRouteImport } from './routes/app/signup'
import { Route as AppReviewsRouteImport } from './routes/app/reviews'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppLoginRouteImport } from './routes/app/login'
import { Route as AppLeadRecoveryRouteImport } from './routes/app/lead-recovery'
import { Route as AppIntegrationsRouteImport } from './routes/app/integrations'
import { Route as AppFollowUpsRouteImport } from './routes/app/follow-ups'
import { Route as AppCompetitorsRouteImport } from './routes/app/competitors'
import { Route as AppChurnRouteImport } from './routes/app/churn'
import { Route as AppAdSpendRouteImport } from './routes/app/ad-spend'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSignupRoute = AppSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AppRoute,
} as any)
const AppReviewsRoute = AppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadRecoveryRoute = AppLeadRecoveryRouteImport.update({
  id: '/lead-recovery',
  path: '/lead-recovery',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppCompetitorsRoute = AppCompetitorsRouteImport.update({
  id: '/competitors',
  path: '/competitors',
  getParentRoute: () => AppRoute,
} as any)
const AppChurnRoute = AppChurnRouteImport.update({
  id: '/churn',
  path: '/churn',
  getParentRoute: () => AppRoute,
} as any)
const AppAdSpendRoute = AppAdSpendRouteImport.update({
  id: '/ad-spend',
  path: '/ad-spend',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/app/ad-spend': typeof AppAdSpendRoute
  '/app/churn': typeof AppChurnRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/lead-recovery': typeof AppLeadRecoveryRoute
  '/app/login': typeof AppLoginRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/signup': typeof AppSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/app/ad-spend': typeof AppAdSpendRoute
  '/app/churn': typeof AppChurnRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/lead-recovery': typeof AppLeadRecoveryRoute
  '/app/login': typeof AppLoginRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/signup': typeof AppSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/audit': typeof AuditRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/app/ad-spend': typeof AppAdSpendRoute
  '/app/churn': typeof AppChurnRoute
  '/app/competitors': typeof AppCompetitorsRoute
  '/app/follow-ups': typeof AppFollowUpsRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/lead-recovery': typeof AppLeadRecoveryRoute
  '/app/login': typeof AppLoginRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/reviews': typeof AppReviewsRoute
  '/app/signup': typeof AppSignupRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/audit'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/pricing'
    | '/app/ad-spend'
    | '/app/churn'
    | '/app/competitors'
    | '/app/follow-ups'
    | '/app/integrations'
    | '/app/lead-recovery'
    | '/app/login'
    | '/app/onboarding'
    | '/app/reviews'
    | '/app/signup'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/pricing'
    | '/app/ad-spend'
    | '/app/churn'
    | '/app/competitors'
    | '/app/follow-ups'
    | '/app/integrations'
    | '/app/lead-recovery'
    | '/app/login'
    | '/app/onboarding'
    | '/app/reviews'
    | '/app/signup'
    | '/blog/$slug'
    | '/app'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/audit'
    | '/contact'
    | '/features'
    | '/how-it-works'
    | '/pricing'
    | '/app/ad-spend'
    | '/app/churn'
    | '/app/competitors'
    | '/app/follow-ups'
    | '/app/integrations'
    | '/app/lead-recovery'
    | '/app/login'
    | '/app/onboarding'
    | '/app/reviews'
    | '/app/signup'
    | '/blog/$slug'
    | '/app/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuditRoute: typeof AuditRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/signup': {
      id: '/app/signup'
      path: '/signup'
      fullPath: '/app/signup'
      preLoaderRoute: typeof AppSignupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reviews': {
      id: '/app/reviews'
      path: '/reviews'
      fullPath: '/app/reviews'
      preLoaderRoute: typeof AppReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/login': {
      id: '/app/login'
      path: '/login'
      fullPath: '/app/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lead-recovery': {
      id: '/app/lead-recovery'
      path: '/lead-recovery'
      fullPath: '/app/lead-recovery'
      preLoaderRoute: typeof AppLeadRecoveryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/follow-ups': {
      id: '/app/follow-ups'
      path: '/follow-ups'
      fullPath: '/app/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/competitors': {
      id: '/app/competitors'
      path: '/competitors'
      fullPath: '/app/competitors'
      preLoaderRoute: typeof AppCompetitorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/churn': {
      id: '/app/churn'
      path: '/churn'
      fullPath: '/app/churn'
      preLoaderRoute: typeof AppChurnRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/ad-spend': {
      id: '/app/ad-spend'
      path: '/ad-spend'
      fullPath: '/app/ad-spend'
      preLoaderRoute: typeof AppAdSpendRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdSpendRoute: typeof AppAdSpendRoute
  AppChurnRoute: typeof AppChurnRoute
  AppCompetitorsRoute: typeof AppCompetitorsRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppLeadRecoveryRoute: typeof AppLeadRecoveryRoute
  AppLoginRoute: typeof AppLoginRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppReviewsRoute: typeof AppReviewsRoute
  AppSignupRoute: typeof AppSignupRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdSpendRoute: AppAdSpendRoute,
  AppChurnRoute: AppChurnRoute,
  AppCompetitorsRoute: AppCompetitorsRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppLeadRecoveryRoute: AppLeadRecoveryRoute,
  AppLoginRoute: AppLoginRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppReviewsRoute: AppReviewsRoute,
  AppSignupRoute: AppSignupRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuditRoute: AuditRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
